package entity;
// Generated 22-abr-2017 5:54:52 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Books generated by hbm2java
 */
public class Books  implements java.io.Serializable {


     private String titulo;
     private String autor;
     private String tema;
     private String ocupado;
     private byte[] imagen;

    public Books() {
    }

	
    public Books(String titulo) {
        this.titulo = titulo;
    }
    public Books(String titulo, String autor, String tema, String ocupado, byte[] imagen) {
       this.titulo = titulo;
       this.autor = autor;
       this.tema = tema;
       this.ocupado = ocupado;
       this.imagen = imagen;
    }
   
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }
    public String getOcupado() {
        return this.ocupado;
    }
    
    public void setOcupado(String ocupado) {
        this.ocupado = ocupado;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }




}


